"""
Pydantic models for FastAPI request and response.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class MessageContent(BaseModel):
    """Represents a single message in the conversation."""
    sender: str = Field(..., description="The sender of the message (e.g., 'scammer', 'user', 'honeypot-agent').")
    text: str = Field(..., description="The content of the message.")
    timestamp: str = Field(..., description="ISO 8601 formatted timestamp of when the message was sent.")

class IncomingMessage(BaseModel):
    """
    Model for the incoming request to the /analyze endpoint.
    """
    sessionId: str = Field(..., description="Unique identifier for the conversation session.")
    message: MessageContent = Field(..., description="The latest incoming message from the scammer.")
    conversationHistory: List[MessageContent] = Field(default_factory=list, description="A list of previous messages in the conversation (scammer and agent responses).")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context/metadata (e.g., channel, language, locale).")

class ExtractedIntelligence(BaseModel):
    """
    Model for extracted intelligence.
    """
    bankAccounts: List[str] = Field(default_factory=list, description="List of extracted bank account numbers.")
    upiIds: List[str] = Field(default_factory=list, description="List of extracted UPI IDs.")
    phishingLinks: List[str] = Field(default_factory=list, description="List of extracted phishing links/URLs.")
    phoneNumbers: List[str] = Field(default_factory=list, description="List of extracted phone numbers.")
    suspiciousKeywords: List[str] = Field(default_factory=list, description="List of extracted suspicious keywords.")

class EngagementMetrics(BaseModel):
    """
    Model for engagement metrics related to the conversation.
    """
    conversationTurn: int = Field(..., description="The current turn number of the conversation.")
    responseTimeMs: int = Field(..., description="The response time of the agent in milliseconds.")
    totalIntelligenceItems: int = Field(..., description="The total number of intelligence items extracted so far.")
    confidenceScore: float = Field(..., description="The confidence score of scam detection for the current message.")

class ApiResponse(BaseModel):
    """
    Model for the response returned by the /analyze endpoint.
    """
    status: str = Field(..., description="Status of the response (e.g., 'success', 'error').")
    scamDetected: bool = Field(..., description="True if a scam was detected in the current message.")
    agentResponse: str = Field(..., description="The human-like response generated by the Actor Agent.")
    extractedIntelligence: ExtractedIntelligence = Field(..., description="A dictionary containing all extracted intelligence.")
    engagementMetrics: EngagementMetrics = Field(..., description="Metrics related to the conversation engagement.")
    continueConversation: bool = Field(..., description="True if the conversation should continue, False if it should end.")
    agentNotes: str = Field(..., description="Notes from the agent, typically the reason for scam detection.")
